env:
  SOURCE_DATABASE_TYPE: "mysql"
  SOURCE_DATABASE_NAME: "my_database"
  SOURCE_DATABASE_USER: "root"
  SOURCE_DATABASE_PASSWORD: "my_mysql_password"

  TARGET_DATABASE_TYPE: "postgresql"
  TARGET_DATABASE_NAME: "pg_default"
  TARGET_DATABASE_USER: "postgres"
  TARGET_DATABASE_PASSWORD: "my_pg_password"

source-mariadb:
  # See https://github.com/bitnami/charts/blob/main/bitnami/mariadb/values.yaml
  enabled: true
  image:
  tag: 10.5.13-debian-10-r32
  primary:
    persistence:
      existingClaim: "my-source-database-pvc"
  extraDeploy:
  - |
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: migrate-db-src
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      dataSource:
        kind: PersistentVolumeClaim
        name: db-orig

target-postgresql:
  # See https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  enabled: true
  primary:
    persistence:
      existingClaim: "my-target-database-pvc"
