
env:
  # Fill in here connection detail for the source database:
  SOURCE_DATABASE_TYPE: "mysql"
  SOURCE_DATABASE_NAME: "my_database"
  SOURCE_DATABASE_HOST: "{{ .Release.Name }}-source-db"
  SOURCE_DATABASE_USER: "root"
  SOURCE_DATABASE_PASSWORD: "my_mysql_password"

  # Fill in here connection detail for the target database:
  TARGET_DATABASE_TYPE: "postgresql"
  TARGET_DATABASE_NAME: "pg_default"
  TARGET_DATABASE_HOST: "{{ .Release.Name }}-target-db"
  TARGET_DATABASE_USER: "postgres"
  TARGET_DATABASE_PASSWORD: "my_pg_password"

# Enable databases that are used in the migration:
source:
  mysql:
    enabled: false
  mariadb:
    enabled: false
  postgresql:
    enabled: false

# You can optionally specify the exact tag of the database server and connect
# an existing PVC like this:
# source-mariadb:
#   image:
#     tag: 10.5.13-debian-10-r32
#   primary:
#     persistence:
#       existingClaim: "my-source-database"
# The same approach is for other databases, including target ones.

target:
  mysql:
    enabled: false
  mariadb:
    enabled: false
  postgresql:
    enabled: false


source-mariadb:
    nameOverride: source-db
source-mysql:
    nameOverride: source-db
source-postgresql:
    nameOverride: source-db

target-mariadb:
    nameOverride: target-db
target-mysql:
    nameOverride: target-db
target-postgresql:
    nameOverride: target-db
