apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-job-pgloader-{{ .Release.Revision }}"
spec:
  template:
    metadata:
      labels:
        job-version: "{{ .Release.Revision }}"
    spec:
      containers:
      - name: pgloader
        image: dimitri/pgloader
        # command: ["sleep", "infinity"]
        command: ["pgloader", "/db-migrate.load"]
        envFrom:
        - secretRef:
            name: "{{ .Release.Name }}-job-{{ .Release.Revision }}-env"
        volumeMounts:
        - name: pgloader
          mountPath: /db-migrate.load
          subPath: "db-migrate.load"
      volumes:
        - name: pgloader
          secret:
            secretName: "{{ .Release.Name }}-job-{{ .Release.Revision }}-pgloader"

      restartPolicy: Never
