apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-job-{{ .Release.Revision }}-env"

data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ tpl $value $ | toString | b64enc | quote }}
{{- end }}
