apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-job-{{ .Release.Revision }}-pgloader"

stringData:
  db-migrate.load: |
    LOAD DATABASE
      FROM {{ .Values.env.SOURCE_DATABASE_TYPE }}://{{ .Values.env.SOURCE_DATABASE_USER }}:{{ .Values.env.SOURCE_DATABASE_PASSWORD }}@db-migrate-source-db/{{ .Values.env.SOURCE_DATABASE_NAME }}
      INTO {{ .Values.env.TARGET_DATABASE_TYPE }}://{{ .Values.env.TARGET_DATABASE_USER }}:{{ .Values.env.TARGET_DATABASE_PASSWORD }}@db-migrate-target-db/{{ .Values.env.TARGET_DATABASE_NAME }}
      WITH data only
      EXCLUDING TABLE NAMES MATCHING '__diesel_schema_migrations'
      ALTER SCHEMA '{{ .Values.env.SOURCE_DATABASE_NAME }}' RENAME TO 'public'
    ;
