apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-env-{{ .Release.Revision }}"
  # name: "{{ .Release.Name }}-env"

data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
